### ISSUE TITLE
`crypton-x509-store-1.6.12` build failure with `unix-2.7.3` (GHC 9.4.8)

### ISSUE THREAD

**Issue by RyanGlScott** [kazu-yamamoto/crypton-certificate#21]
`crypton-x509-store-1.6.12` fails to build with `unix-2.7.3`, which is bundled with GHC 9.4.8:

```
$ cabal build
Build profile: -w ghc-9.4.8 -O1
In order, the following will be built (use -v for more details):
 - crypton-x509-store-1.6.12 (lib) (first run)
Preprocessing library for crypton-x509-store-1.6.12...
Building library for crypton-x509-store-1.6.12...
[3 of 3] Compiling Data.X509.File   ( Data/X509/File.hs, dist-newstyle/build/x86_64-linux/ghc-9.4.8/crypton-x509-store-1.6.12/build/Data/X509/File.o, dist-newstyle/build/x86_64-linux/ghc-9.4.8/crypton-x509-store-1.6.12/build/Data/X509/File.dyn_o )

Data/X509/File.hs:34:53: error: Not in scope: ‘cloexec’
   |
34 |     fd <- openFd filepath ReadOnly defaultFileFlags{cloexec = True}
   |                                                     ^^^^^^^
Error: [Cabal-7125]
Failed to build crypton-x509-store-1.6.12.
```

This is because `unix`'s [`cloexec`](https://hackage-content.haskell.org/package/unix-2.8.8.0/docs/System-Posix-IO.html#v:cloexec) field is only available since `unix-2.8.0.0` or later, and GHC 9.4.8 does not bundle this version of `unix`.

**Comment by sol** [comment]
This is currently breaking the Hpack build:

https://github.com/sol/hpack/actions/runs/18810752471/job/53671540882

@kazu-yamamoto can you please add a Hackage revision to address this?  Or alternatively, @andreasabel can you step in?

**Comment by sol** [comment]
At least the Hpack build seems to succeed now.

Thank you @kazu-yamamoto.
