### ISSUE TITLE
crypton-x509-store build failure

### ISSUE THREAD

**Issue by jgm** [kazu-yamamoto/crypton-certificate#27]
I'm seeing this in my [Windows CI](https://github.com/jgm/pandoc/actions/runs/20809676531/job/59770801628) with the newest version 1.6.13:
```
Failed to build crypton-x509-store-1.6.13.
Build log (
C:\cabal\logs\ghc-9.10.3\crypton-x509-_-1.6.13-a211e9b61880ad81bf893cb307c738856b1002e8.log
):
Preprocessing library for crypton-x509-store-1.6.13...
Building library for crypton-x509-store-1.6.13...
Data\X509\File.hs:19:35: error:
     error: function-like macro 'MIN_VERSION_unix' is not defined
   |
19 | #if !defined(mingw32_HOST_OS) && (MIN_VERSION_unix(2,8,0))
   |                                   ^

#if !defined(mingw32_HOST_OS) && (MIN_VERSION_unix(2,8,0))
                                  ^
Data\X509\File.hs:31:35: error:
     error: function-like macro 'MIN_VERSION_unix' is not defined
   |
31 | #if defined(mingw32_HOST_OS) || !(MIN_VERSION_unix(2,8,0))
   |                                   ^

#if defined(mingw32_HOST_OS) || !(MIN_VERSION_unix(2,8,0))
                                  ^
2 errors generated.
```

PS. It would be great if this project had its own CI to catch issues like this!

**Comment by kazu-yamamoto** [comment]
> PS. It would be great if this project had its own CI to catch issues like this!

I have added `window-latest` to CI.

**Comment by kazu-yamamoto** [comment]
Caused by #23.
Cc: @khibino

**Comment by kazu-yamamoto** [comment]
In addition to @Bodigrim's approach, @tfausak's is also necessary.
See 111f377.
I'm going to release v1.6.14 and deprecate v1.6.13.
